services:
  db:
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:setup && bundle exec rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    env_file:
      - .env

volumes:
  postgres-data:
